spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-description: "first"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: product-service
  server:
    port: 8050